export const T = {
  en: {
    tagline: "Explore. Learn. Smile.",
    missionTitle: "🩺 Your Mission",
    missionText: "You are a young dentist visiting a school to run a preventive dental campaign. Guide students to better oral health habits. Each correct choice earns points and improves the Community Oral Health Meter!",
    tags: ["27 Questions", "3 Sets", "Bilingual", "All Ages"],
    startBtn: "Start Your Odyssey 🚀",
    levelLabel: "Level",
    communityHealth: "Community Health",
    healthLabels: { good: "Excellent", fair: "Fair", poor: "Poor" },
    results: { best: "Best Choice!", okay: "Good Thinking!", wrong: "Not Quite!" },
    unlocked: "🎁 Unlocked:",
    pts: "pts",
    health: "health",
    nextLevel: "Next Level →",
    getPromoted: "🎉 Get Promoted!",
    finalResults: "See Final Results 🏁",
    continueJourney: "Continue Journey →",
    promotionTitle: "Promotion!",
    congratulations: "Congratulations!",
    promotedFrom: "You've been promoted from",
    odysseyComplete: "Odyssey Complete!",
    finalScore: "Final Score",
    performance: "Performance",
    communityHealthStat: "Community Health",
    badgesEarned: "Badges Earned",
    collection: "🎒 Your Collection",
    tipTitle: "💡 Remember:",
    tipText: "Brush twice daily, visit your dentist regularly, limit sugary foods, and share your knowledge with others. Every healthy smile starts with a good habit!",
    playAgain: "Play Again 🔄",
    scenario: "Scenario",
    grades: { champion: "Oral Health Champion!", good: "Good Dental Advocate!", keep: "Keep Learning!" },
    ranks: ["Junior Dentist", "Senior Dentist", "Community Dental Leader", "Public Health Specialist"],

    viewReport: "View Report 📊",
    teacherDashboard: "Teacher/Parent Dashboard",
    studentPerformance: "Student Performance",
    categoryBreakdown: "Performance by Category",
    detailedResults: "Detailed Results",
    recommendations: "Recommendations",
    printReport: "Print Report 🖨️",
    backToResults: "Back to Results",
    categories: {
      prevention: "Prevention & Habits",
      nutrition: "Nutrition & Diet",
      professional: "Professional Care",
      lifestyle: "Lifestyle Choices",
      technology: "Technology & Innovation",
    },
    setName: "Set",
    setsPlayed: "Sets Explored",
    randomSet: "🎲 Random Set Selected!",
    newSetDiscovered: "🌟 New Set Discovered!",
    allSetsComplete: "🏆 Master Explorer! You've completed all sets!",
    setThemes: {
      set1: { name: "Daily Habits", desc: "Master the basics of preventive oral care", icon: "🛡️" },
      set2: { name: "Real-Life Scenarios", desc: "Handle everyday dental challenges", icon: "🌍" },
      set3: { name: "Advanced Care", desc: "Explore advanced oral health topics", icon: "🎓" },
    },
  },
  my: {
    tagline: "Jelajah. Belajar. Senyum.",
    missionTitle: "🩺 Misi Kamu",
    missionText: "Kamu adalah seorang doktor gigi muda yang melawat sebuah sekolah untuk menjalankan kempen pergigian pencegahan. Pandukan pelajar ke arah tabiat kesihatan oral yang lebih baik. Setiap pilihan betul memberi kamu mata dan meningkatkan Meter Kesihatan Oral Komuniti!",
    tags: ["27 Soalan", "3 Set", "Dwibahasa", "Semua Peringkat Umur"],
    startBtn: "Mulakan Odyssey Kamu 🚀",
    levelLabel: "Tahap",
    communityHealth: "Kesihatan Komuniti",
    healthLabels: { good: "Cemerlang", fair: "Sederhana", poor: "Lemah" },
    results: { best: "Pilihan Terbaik!", okay: "Bagus Juga!", wrong: "Tidak Tepat!" },
    unlocked: "🎁 Terbuka:",
    pts: "mata",
    health: "kesihatan",
    nextLevel: "Tahap Seterusnya →",
    getPromoted: "🎉 Naik Pangkat!",
    finalResults: "Lihat Keputusan Akhir 🏁",
    continueJourney: "Teruskan Perjalanan →",
    promotionTitle: "Kenaikan Pangkat!",
    congratulations: "Tahniah!",
    promotedFrom: "Kamu telah dinaikkan pangkat daripada",
    odysseyComplete: "Odyssey Selesai!",
    finalScore: "Markah Akhir",
    performance: "Prestasi",
    communityHealthStat: "Kesihatan Komuniti",
    badgesEarned: "Lencana Diperolehi",
    collection: "🎒 Koleksi Kamu",
    tipTitle: "💡 Ingat:",
    tipText: "Berus gigi dua kali sehari, lawati doktor gigi secara berkala, hadkan makanan bergula, dan kongsi ilmu dengan orang lain. Setiap senyuman sihat bermula dengan tabiat yang baik!",
    playAgain: "Main Semula 🔄",
    scenario: "Senario",
    grades: { champion: "Juara Kesihatan Oral!", good: "Peguam Pergigian Yang Baik!", keep: "Teruskan Belajar!" },
    ranks: ["Doktor Gigi Muda", "Doktor Gigi Kanan", "Pemimpin Pergigian Komuniti", "Pakar Kesihatan Awam"],

    viewReport: "Lihat Laporan 📊",
    teacherDashboard: "Papan Pemuka Guru/Ibu Bapa",
    studentPerformance: "Prestasi Pelajar",
    categoryBreakdown: "Prestasi Mengikut Kategori",
    detailedResults: "Keputusan Terperinci",
    recommendations: "Cadangan",
    printReport: "Cetak Laporan 🖨️",
    backToResults: "Kembali ke Keputusan",
    categories: {
      prevention: "Pencegahan & Tabiat",
      nutrition: "Pemakanan & Diet",
      professional: "Penjagaan Profesional",
      lifestyle: "Pilihan Gaya Hidup",
      technology: "Teknologi & Inovasi",
    },
    setName: "Set",
    setsPlayed: "Set Diterokai",
    randomSet: "🎲 Set Rawak Dipilih!",
    newSetDiscovered: "🌟 Set Baru Ditemui!",
    allSetsComplete: "🏆 Penjelajah Pakar! Anda telah lengkapkan semua set!",
    setThemes: {
      set1: { name: "Tabiat Harian", desc: "Kuasai asas penjagaan oral pencegahan", icon: "🛡️" },
      set2: { name: "Senario Kehidupan", desc: "Hadapi cabaran pergigian harian", icon: "🌍" },
      set3: { name: "Penjagaan Lanjutan", desc: "Terokai topik kesihatan oral lanjutan", icon: "🎓" },
    },
  },
};

export const SETS = {
  set1: {
    en: [
      { id: 1, emoji: "🪥", title: "Brushing Basics", category: "prevention",
        scenario: "Your friend says he only brushes once at night because he's too lazy in the morning.",
        options: [
          { label: "A", text: "Remind him to brush morning & night, 2 minutes each.", result: "best", feedback: "⭐ Perfect! Brushing twice daily removes plaque effectively!", points: 100, health: 20, unlock: "🪥 Toothbrush Upgrade" },
          { label: "B", text: "Tell him it's okay, at least he brushes once.", result: "wrong", feedback: "❌ Plaque builds up overnight AND during the day. Brushing once isn't enough — bad breath and caries risk rise!", points: 0, health: -15 },
          { label: "C", text: "Tell him to just use mouthwash instead.", result: "wrong", feedback: "❌ Mouthwash is a supplement, not a replacement! Cavities will appear.", points: 0, health: -10 },
        ],
      },
      { id: 2, emoji: "🧋", title: "Sugary Drinks", category: "nutrition",
        scenario: "After school, your classmates buy bubble tea. They ask you to join.",
        options: [
          { label: "A", text: "Buy large bubble tea with extra sugar.", result: "wrong", feedback: "❌ High sugar feeds bacteria that cause tooth decay!", points: 0, health: -15 },
          { label: "B", text: "Refuse completely and only drink water.", result: "okay", feedback: "✅ Very healthy for teeth! Balance is also fine though.", points: 50, health: 10 },
          { label: "C", text: "Choose a smaller size with less sugar, drink with a straw.", result: "best", feedback: "⭐ Smart move! Using a straw reduces sugar contact with teeth!", points: 100, health: 20, unlock: "🔍 Sugar Detective Badge" },
        ],
      },
      { id: 3, emoji: "🦷", title: "Dentist Visit", category: "professional",
        scenario: "Your cousin hasn't been to the dentist in 3 years and is scared.",
        options: [
          { label: "A", text: "Tell him to wait until a tooth really hurts.", result: "wrong", feedback: "❌ Waiting for pain means late treatment — sometimes extraction!", points: 0, health: -10 },
          { label: "B", text: "Encourage him to go for a check-up. Prevention is better!", result: "best", feedback: "⭐ Excellent! Regular check-ups catch problems early!", points: 100, health: 20, unlock: "🪞 Dental Mirror Tool" },
          { label: "C", text: "Say \"don't worry, you don't need a dentist if nothing hurts.\"", result: "wrong", feedback: "❌ Pain comes later — by then, untreated cavities become serious!", points: 0, health: -15 },
        ],
        promotion: { fromKey: 0, toKey: 1, emoji: "🎓" },
      },
      { id: 4, emoji: "😬", title: "Braces Care", category: "prevention",
        scenario: "Your friend with braces says it's too hard to brush, so he skips.",
        options: [
          { label: "A", text: "Say \"braces already protect teeth, no need to brush much.\"", result: "wrong", feedback: "❌ Wrong! Plaque around brackets causes white spots and decay!", points: 0, health: -15 },
          { label: "B", text: "Just tell him to avoid sticky food, brushing is optional.", result: "wrong", feedback: "❌ Food still gets trapped in braces. Brushing is essential!", points: 0, health: -10 },
          { label: "C", text: "Suggest a special orthodontic brush & floss threader.", result: "best", feedback: "⭐ Great advice! The right tools make braces care effective!", points: 100, health: 20, unlock: "🧰 Braces Care Kit" },
        ],
      },
      { id: 5, emoji: "💧", title: "Fluoride Power", category: "prevention",
        scenario: "A teacher says school water has fluoride. Some students say it's harmful.",
        options: [
          { label: "A", text: "Explain fluoride makes teeth stronger & is safe at correct levels.", result: "best", feedback: "⭐ Spot on! Science-backed knowledge wins!", points: 100, health: 20, unlock: "🛡️ Fluoride Shield Power" },
          { label: "B", text: "Say you're not sure, maybe better to avoid.", result: "okay", feedback: "✅ Caution is okay, but evidence-based knowledge is better.", points: 50, health: 5 },
          { label: "C", text: "Agree fluoride is dangerous and avoid it.", result: "wrong", feedback: "❌ At correct levels, fluoride is safe and prevents decay!", points: 0, health: -15 },
        ],
      },
      { id: 6, emoji: "⚽", title: "Mouthguards & Sports", category: "prevention",
        scenario: "During football practice, a friend gets a chipped tooth.",
        options: [
          { label: "A", text: "Suggest chewing gum to strengthen teeth instead.", result: "wrong", feedback: "❌ Gum doesn't protect against impacts!", points: 0, health: -10 },
          { label: "B", text: "Tell everyone to wear mouthguards for sports.", result: "best", feedback: "⭐ Champion decision! Mouthguards prevent injuries!", points: 100, health: 20, unlock: "🏅 Mouthguard Upgrade" },
          { label: "C", text: "Say \"teeth are strong, don't worry.\"", result: "wrong", feedback: "❌ Tooth fractures worsen without care!", points: 0, health: -15 },
        ],
        promotion: { fromKey: 1, toKey: 2, emoji: "🏆" },
      },
      { id: 7, emoji: "🚭", title: "Tobacco Temptation", category: "lifestyle",
        scenario: "A senior offers you a cigarette, saying it's cool.",
        options: [
          { label: "A", text: "Pretend to accept but throw it away secretly.", result: "okay", feedback: "✅ You avoided harm, but missed a teaching moment!", points: 50, health: 5 },
          { label: "B", text: "Refuse and explain smoking damages teeth and gums.", result: "best", feedback: "⭐ Courageous and wise! You protect AND educate!", points: 100, health: 20, unlock: "🚭 Anti-Smoking Badge" },
          { label: "C", text: "Say yes, try it once.", result: "wrong", feedback: "❌ Even one cigarette starts damage — gum disease risk!", points: 0, health: -20 },
        ],
      },
      { id: 8, emoji: "🔒", title: "Seal the Deal", category: "professional",
        scenario: "A dentist offers pit & fissure sealants for your sibling's molars.",
        options: [
          { label: "A", text: "Agree — sealants protect molars from cavities.", result: "best", feedback: "⭐ Excellent! Sealants are top preventive tools!", points: 100, health: 20, unlock: "🔒 Sealant Power" },
          { label: "B", text: "Say it's unnecessary, brushing is enough.", result: "wrong", feedback: "❌ Deep grooves in molars are hard to clean. Sealants protect them!", points: 0, health: -15 },
          { label: "C", text: "Say you'll wait until the tooth hurts first.", result: "wrong", feedback: "❌ By then it's too late — cavity already formed!", points: 0, health: -10 },
        ],
      },
      { id: 9, emoji: "📱", title: "Digital Dentistry", category: "technology",
        scenario: "A new school program uses an app to track brushing habits.",
        options: [
          { label: "A", text: "Join quietly but don't remind others.", result: "okay", feedback: "✅ Some benefit, but a leader brings others along!", points: 50, health: 8 },
          { label: "B", text: "Say it's spying, refuse to join.", result: "wrong", feedback: "❌ You lose monitoring benefits and chance to improve!", points: 0, health: -10 },
          { label: "C", text: "Join and encourage friends — data helps habits.", result: "best", feedback: "⭐ Brilliant! Tech for health is the future!", points: 100, health: 20, unlock: "📱 Smart Oral Health App" },
        ],
        promotion: { fromKey: 2, toKey: 3, emoji: "🌟" },
      },
    ],
    my: [
      { id: 1, emoji: "🪥", title: "Asas Memberus Gigi", category: "prevention",
        scenario: "Kawan kamu hanya memberus gigi sekali pada waktu malam kerana malas pada waktu pagi.",
        options: [
          { label: "A", text: "Ingatkan dia memberus pagi dan malam, 2 minit setiap kali.", result: "best", feedback: "⭐ Sempurna! Memberus dua kali sehari mengalihkan plak!", points: 100, health: 20, unlock: "🪥 Naik Taraf Berus Gigi" },
          { label: "B", text: "Beritahunya tak apa, sekurang-kurangnya dia memberus.", result: "wrong", feedback: "❌ Plak terbina sepanjang malam dan siang. Sekali tidak cukup!", points: 0, health: -15 },
          { label: "C", text: "Beritahunya guna ubat kumur sahaja.", result: "wrong", feedback: "❌ Ubat kumur tambahan, bukan pengganti! Kaviti akan muncul.", points: 0, health: -10 },
        ],
      },
      { id: 2, emoji: "🧋", title: "Minuman Bergula", category: "nutrition",
        scenario: "Selepas sekolah, rakan sekelas membeli teh buih. Mereka menjemput kamu.",
        options: [
          { label: "A", text: "Beli teh buih besar dengan gula tambahan.", result: "wrong", feedback: "❌ Gula tinggi memberi makan bakteria penyebab kerosakan gigi!", points: 0, health: -15 },
          { label: "B", text: "Tolak sama sekali dan minum air sahaja.", result: "okay", feedback: "✅ Sangat sihat! Tetapi keseimbangan juga ok.", points: 50, health: 10 },
          { label: "C", text: "Pilih saiz lebih kecil, kurang gula, guna straw.", result: "best", feedback: "⭐ Pilihan bijak! Straw mengurangkan sentuhan gula!", points: 100, health: 20, unlock: "🔍 Lencana Detektif Gula" },
        ],
      },
      { id: 3, emoji: "🦷", title: "Lawatan Doktor Gigi", category: "professional",
        scenario: "Sepupu kamu tidak ke doktor gigi selama 3 tahun dan takut.",
        options: [
          { label: "A", text: "Beritahunya tunggu sehingga gigi sakit.", result: "wrong", feedback: "❌ Tunggu sakit bermakna rawatan lewat — mungkin cabutan!", points: 0, health: -10 },
          { label: "B", text: "Galakkan dia pergi untuk pemeriksaan.", result: "best", feedback: "⭐ Cemerlang! Pemeriksaan berkala mengesan masalah awal!", points: 100, health: 20, unlock: "🪞 Alat Cermin Pergigian" },
          { label: "C", text: "Kata \"jangan risau, tak perlu kalau tak sakit.\"", result: "wrong", feedback: "❌ Sakit datang kemudian — kaviti jadi serius!", points: 0, health: -15 },
        ],
        promotion: { fromKey: 0, toKey: 1, emoji: "🎓" },
      },
      { id: 4, emoji: "😬", title: "Penjagaan Pendakap", category: "prevention",
        scenario: "Kawan dengan pendakap kata susah memberus, jadi dia langkau.",
        options: [
          { label: "A", text: "Kata \"pendakap dah lindungi gigi, tak perlu memberus.\"", result: "wrong", feedback: "❌ Salah! Plak di sekeliling braket menyebabkan kerosakan!", points: 0, health: -15 },
          { label: "B", text: "Suruh elak makanan melekit, memberus pilihan.", result: "wrong", feedback: "❌ Makanan masih tersekat. Memberus adalah penting!", points: 0, health: -10 },
          { label: "C", text: "Cadangkan berus ortodontik & benang gigi.", result: "best", feedback: "⭐ Nasihat bagus! Alatan betul menjadikan penjagaan berkesan!", points: 100, health: 20, unlock: "🧰 Kit Penjagaan Pendakap" },
        ],
      },
      { id: 5, emoji: "💧", title: "Kekuatan Fluorida", category: "prevention",
        scenario: "Guru kata air sekolah ada fluorida. Sesetengah pelajar kata berbahaya.",
        options: [
          { label: "A", text: "Jelaskan fluorida menguatkan gigi & selamat.", result: "best", feedback: "⭐ Tepat! Pengetahuan berasaskan sains menang!", points: 100, health: 20, unlock: "🛡️ Kuasa Perisai Fluorida" },
          { label: "B", text: "Kata tidak pasti, lebih baik elakkan.", result: "okay", feedback: "✅ Berhati-hati ok, tapi pengetahuan berasaskan bukti lebih baik.", points: 50, health: 5 },
          { label: "C", text: "Bersetuju fluorida berbahaya dan elakkannya.", result: "wrong", feedback: "❌ Pada tahap betul, fluorida selamat dan mencegah kerosakan!", points: 0, health: -15 },
        ],
      },
      { id: 6, emoji: "⚽", title: "Pelindung Mulut & Sukan", category: "prevention",
        scenario: "Semasa latihan bola sepak, kawan kamu patah gigi.",
        options: [
          { label: "A", text: "Cadangkan kunyah gula-gula getah untuk kuatkan gigi.", result: "wrong", feedback: "❌ Getah tidak melindungi daripada hentaman!", points: 0, health: -10 },
          { label: "B", text: "Beritahu semua pakai pelindung mulut semasa bersukan.", result: "best", feedback: "⭐ Keputusan cemerlang! Pelindung mulut mencegah kecederaan!", points: 100, health: 20, unlock: "🏅 Naik Taraf Pelindung Mulut" },
          { label: "C", text: "Kata \"gigi kuat, jangan risau.\"", result: "wrong", feedback: "❌ Patahan gigi bertambah teruk tanpa rawatan!", points: 0, health: -15 },
        ],
        promotion: { fromKey: 1, toKey: 2, emoji: "🏆" },
      },
      { id: 7, emoji: "🚭", title: "Godaan Tembakau", category: "lifestyle",
        scenario: "Senior menawarkan rokok kepada kamu, kata ia 'cool'.",
        options: [
          { label: "A", text: "Pura-pura terima tapi buang secara senyap.", result: "okay", feedback: "✅ Kamu elak bahaya, tapi terlepas peluang mengajar!", points: 50, health: 5 },
          { label: "B", text: "Tolak dan jelaskan merokok merosakkan gigi dan gusi.", result: "best", feedback: "⭐ Berani dan bijak! Kamu lindungi DAN didik!", points: 100, health: 20, unlock: "🚭 Lencana Anti-Merokok" },
          { label: "C", text: "Kata ya, cuba sekali.", result: "wrong", feedback: "❌ Sebatang pun mula merosakkan — risiko penyakit gusi!", points: 0, health: -20 },
        ],
      },
      { id: 8, emoji: "🔒", title: "Sealant Gigi", category: "professional",
        scenario: "Doktor gigi menawarkan sealant untuk geraham adik kamu.",
        options: [
          { label: "A", text: "Bersetuju — sealant melindungi geraham dari kaviti.", result: "best", feedback: "⭐ Cemerlang! Sealant alat pencegahan terbaik!", points: 100, health: 20, unlock: "🔒 Kuasa Sealant" },
          { label: "B", text: "Kata tidak perlu, memberus sudah cukup.", result: "wrong", feedback: "❌ Alur dalam geraham susah dibersihkan. Sealant melindungi!", points: 0, health: -15 },
          { label: "C", text: "Kata tunggu sehingga gigi sakit dulu.", result: "wrong", feedback: "❌ Masa itu sudah terlambat — kaviti dah terbentuk!", points: 0, health: -10 },
        ],
      },
      { id: 9, emoji: "📱", title: "Pergigian Digital", category: "technology",
        scenario: "Program sekolah baru guna aplikasi untuk jejak tabiat memberus.",
        options: [
          { label: "A", text: "Sertai senyap tapi tidak ingatkan orang lain.", result: "okay", feedback: "✅ Sedikit faedah, tapi pemimpin bawa orang lain bersama!", points: 50, health: 8 },
          { label: "B", text: "Kata ia mengintip, enggan menyertai.", result: "wrong", feedback: "❌ Hilang faedah pemantauan dan peluang memperbaiki!", points: 0, health: -10 },
          { label: "C", text: "Sertai dan galakkan rakan — data bantu tabiat.", result: "best", feedback: "⭐ Brilliant! Teknologi untuk kesihatan adalah masa depan!", points: 100, health: 20, unlock: "📱 Aplikasi Kesihatan Pintar" },
        ],
        promotion: { fromKey: 2, toKey: 3, emoji: "🌟" },
      },
    ],
  },
  set2: {
    en: [
      { id: 1, emoji: "🧵", title: "Flossing Truth", category: "prevention",
        scenario: "Your sister says flossing is unnecessary because her toothbrush reaches everywhere.",
        options: [
          { label: "A", text: "Show her how to floss daily — it cleans where brushes can't.", result: "best", feedback: "⭐ Perfect! Flossing is the only way to clean between teeth properly!", points: 100, health: 20, unlock: "🧵 Floss Master Badge" },
          { label: "B", text: "Agree — brushing is enough.", result: "wrong", feedback: "❌ Toothbrush bristles can't reach between teeth! 40% of tooth surfaces are missed!", points: 0, health: -15 },
          { label: "C", text: "Tell her to use a toothpick instead.", result: "wrong", feedback: "❌ Toothpicks can damage gums and aren't a real substitute!", points: 0, health: -10 },
        ],
      },
      { id: 2, emoji: "🍋", title: "Acid Attack", category: "nutrition",
        scenario: "You drink lemon water every morning. A friend says it's eroding your teeth.",
        options: [
          { label: "A", text: "Ignore — lemon is healthy.", result: "wrong", feedback: "❌ Citrus acid erodes enamel over time, even though lemon has vitamins!", points: 0, health: -15 },
          { label: "B", text: "Drink with a straw, rinse with water after.", result: "best", feedback: "⭐ Perfect balance! You keep the benefits but protect enamel!", points: 100, health: 20, unlock: "🛡️ Enamel Guard Badge" },
          { label: "C", text: "Stop lemon water completely.", result: "okay", feedback: "✅ Safe, but you lose vitamin C benefits. Moderation works too!", points: 50, health: 8 },
        ],
      },
      { id: 3, emoji: "🚨", title: "Tooth Emergency!", category: "professional",
        scenario: "Your friend gets a tooth knocked out at the playground.",
        options: [
          { label: "A", text: "Pick by the crown, store in milk, see dentist within 30 min.", result: "best", feedback: "⭐ Lifesaver! Milk preserves root cells. Time is critical!", points: 100, health: 25, unlock: "🚨 Emergency Hero Badge" },
          { label: "B", text: "Wash it with soap and water thoroughly.", result: "wrong", feedback: "❌ Soap damages root cells! Only rinse with milk or saline!", points: 0, health: -10 },
          { label: "C", text: "Throw it away, get a fake one later.", result: "wrong", feedback: "❌ A knocked-out tooth can be re-implanted if you act fast!", points: 0, health: -20 },
        ],
        promotion: { fromKey: 0, toKey: 1, emoji: "🎓" },
      },
      { id: 4, emoji: "🩸", title: "Bleeding Gums", category: "prevention",
        scenario: "When you brush, your gums bleed sometimes. You're worried.",
        options: [
          { label: "A", text: "Use whitening toothpaste to fix it.", result: "wrong", feedback: "❌ Whitening doesn't address bleeding — and may irritate gums more!", points: 0, health: -10 },
          { label: "B", text: "Stop brushing that area to avoid bleeding.", result: "wrong", feedback: "❌ This worsens gum disease! Bleeding means inflammation needing more care, not less!", points: 0, health: -15 },
          { label: "C", text: "Brush gently and see a dentist — it's a sign of gingivitis.", result: "best", feedback: "⭐ Smart! Early gingivitis is reversible with proper care!", points: 100, health: 20, unlock: "🛡️ Gum Guardian Badge" },
        ],
      },
      { id: 5, emoji: "👅", title: "Tongue Hygiene", category: "prevention",
        scenario: "Your friend has bad breath even though he brushes twice daily.",
        options: [
          { label: "A", text: "Suggest tongue scraping or brushing the tongue.", result: "best", feedback: "⭐ Excellent! 80% of bad breath comes from tongue bacteria!", points: 100, health: 20, unlock: "👅 Fresh Breath Badge" },
          { label: "B", text: "Recommend chewing gum constantly.", result: "okay", feedback: "✅ Masks the smell but doesn't solve the cause!", points: 50, health: 5 },
          { label: "C", text: "Tell him it's just genetics, nothing to do.", result: "wrong", feedback: "❌ Bad breath usually comes from tongue bacteria — it's treatable!", points: 0, health: -15 },
        ],
      },
      { id: 6, emoji: "🎂", title: "Birthday Party Snacks", category: "nutrition",
        scenario: "You're at a birthday party with cake, candy, and fruit platters.",
        options: [
          { label: "A", text: "Eat sweets throughout the entire party.", result: "wrong", feedback: "❌ Constant sugar = constant acid attacks on teeth!", points: 0, health: -15 },
          { label: "B", text: "Eat sweets in one sitting, then enjoy fruits and cheese.", result: "best", feedback: "⭐ Smart! Less frequent sugar exposure protects teeth!", points: 100, health: 20, unlock: "🎯 Smart Snacker Badge" },
          { label: "C", text: "Skip everything sweet completely.", result: "okay", feedback: "✅ Very strict but safe. Moderation works too!", points: 50, health: 8 },
        ],
        promotion: { fromKey: 1, toKey: 2, emoji: "🏆" },
      },
      { id: 7, emoji: "💨", title: "Vape Trend", category: "lifestyle",
        scenario: "A classmate offers you a vape, saying \"it's just flavored water vapor, totally safe.\"",
        options: [
          { label: "A", text: "Refuse — vaping still damages oral health.", result: "best", feedback: "⭐ Smart! Vaping causes gum disease and dry mouth too!", points: 100, health: 20, unlock: "💨 Vape-Free Badge" },
          { label: "B", text: "Try it — it's just flavored water.", result: "wrong", feedback: "❌ Vapes contain nicotine that harms gums and dries mouth!", points: 0, health: -20 },
          { label: "C", text: "Take a small puff, then refuse more.", result: "wrong", feedback: "❌ Even one puff exposes you to harmful chemicals!", points: 0, health: -10 },
        ],
      },
      { id: 8, emoji: "🦷", title: "Wisdom Teeth Pain", category: "professional",
        scenario: "Your back gum is swollen and sore. Your aunt says it's wisdom teeth coming in.",
        options: [
          { label: "A", text: "See a dentist for X-ray and proper assessment.", result: "best", feedback: "⭐ Wise choice! Early evaluation prevents major surgery later!", points: 100, health: 20, unlock: "🔬 X-Ray Vision Power" },
          { label: "B", text: "Just take painkillers and ignore.", result: "wrong", feedback: "❌ Painkillers mask the problem — infection can spread!", points: 0, health: -10 },
          { label: "C", text: "Wait it out — it'll go away.", result: "wrong", feedback: "❌ Impacted wisdom teeth can become infected — needs assessment!", points: 0, health: -15 },
        ],
      },
      { id: 9, emoji: "📞", title: "Teledentistry", category: "technology",
        scenario: "Your village has no dentist. A new app offers video consultations with real dentists.",
        options: [
          { label: "A", text: "Try video consultation for advice and referrals.", result: "best", feedback: "⭐ Brilliant! Telehealth brings care to underserved areas!", points: 100, health: 20, unlock: "📞 Telehealth Innovator" },
          { label: "B", text: "Wait until you can travel to a city.", result: "okay", feedback: "✅ Cautious but delays needed care!", points: 50, health: 5 },
          { label: "C", text: "Don't trust online doctors.", result: "wrong", feedback: "❌ Teledentistry is verified medicine — you miss valuable care!", points: 0, health: -10 },
        ],
        promotion: { fromKey: 2, toKey: 3, emoji: "🌟" },
      },
    ],
    my: [
      { id: 1, emoji: "🧵", title: "Kebenaran Benang Gigi", category: "prevention",
        scenario: "Kakak kamu kata benang gigi tidak perlu kerana berus giginya capai semua tempat.",
        options: [
          { label: "A", text: "Tunjuk cara guna benang setiap hari.", result: "best", feedback: "⭐ Sempurna! Benang gigi satu-satunya cara bersihkan antara gigi!", points: 100, health: 20, unlock: "🧵 Lencana Pakar Benang" },
          { label: "B", text: "Bersetuju — memberus sudah cukup.", result: "wrong", feedback: "❌ Bulu berus tak boleh capai antara gigi! 40% permukaan terlepas!", points: 0, health: -15 },
          { label: "C", text: "Suruh dia guna pencungkil gigi.", result: "wrong", feedback: "❌ Pencungkil boleh rosakkan gusi dan bukan pengganti!", points: 0, health: -10 },
        ],
      },
      { id: 2, emoji: "🍋", title: "Serangan Asid", category: "nutrition",
        scenario: "Kamu minum air lemon setiap pagi. Kawan kata ia menghakis gigi.",
        options: [
          { label: "A", text: "Abaikan — lemon itu sihat.", result: "wrong", feedback: "❌ Asid sitrus menghakis enamel walaupun lemon ada vitamin!", points: 0, health: -15 },
          { label: "B", text: "Minum dengan straw, kumur dengan air selepasnya.", result: "best", feedback: "⭐ Keseimbangan sempurna! Dapat manfaat tapi lindungi enamel!", points: 100, health: 20, unlock: "🛡️ Lencana Pengawal Enamel" },
          { label: "C", text: "Berhenti minum air lemon sepenuhnya.", result: "okay", feedback: "✅ Selamat tapi hilang vitamin C. Sederhana juga ok!", points: 50, health: 8 },
        ],
      },
      { id: 3, emoji: "🚨", title: "Kecemasan Gigi!", category: "professional",
        scenario: "Kawan kamu tertanggal gigi di taman permainan.",
        options: [
          { label: "A", text: "Pegang mahkota, simpan dalam susu, jumpa doktor dalam 30 minit.", result: "best", feedback: "⭐ Penyelamat! Susu memelihara sel akar. Masa kritikal!", points: 100, health: 25, unlock: "🚨 Lencana Wira Kecemasan" },
          { label: "B", text: "Cuci dengan sabun dan air sepenuhnya.", result: "wrong", feedback: "❌ Sabun rosakkan sel akar! Kumur dengan susu sahaja!", points: 0, health: -10 },
          { label: "C", text: "Buang sahaja, dapatkan gigi palsu kemudian.", result: "wrong", feedback: "❌ Gigi yang tertanggal boleh ditanam semula jika cepat bertindak!", points: 0, health: -20 },
        ],
        promotion: { fromKey: 0, toKey: 1, emoji: "🎓" },
      },
      { id: 4, emoji: "🩸", title: "Gusi Berdarah", category: "prevention",
        scenario: "Bila memberus, gusi kamu berdarah kadang-kadang. Kamu risau.",
        options: [
          { label: "A", text: "Guna ubat gigi pemutih untuk perbaikinya.", result: "wrong", feedback: "❌ Pemutih tidak selesaikan masalah berdarah!", points: 0, health: -10 },
          { label: "B", text: "Berhenti memberus kawasan itu untuk elak berdarah.", result: "wrong", feedback: "❌ Memburukkan penyakit gusi! Berdarah perlu lebih penjagaan, bukan kurang!", points: 0, health: -15 },
          { label: "C", text: "Memberus perlahan dan jumpa doktor — tanda gingivitis.", result: "best", feedback: "⭐ Bijak! Gingivitis awal boleh dipulihkan dengan penjagaan betul!", points: 100, health: 20, unlock: "🛡️ Lencana Pengawal Gusi" },
        ],
      },
      { id: 5, emoji: "👅", title: "Kebersihan Lidah", category: "prevention",
        scenario: "Kawan kamu mulutnya berbau walaupun memberus dua kali sehari.",
        options: [
          { label: "A", text: "Cadangkan pengikis lidah atau berus lidah.", result: "best", feedback: "⭐ Cemerlang! 80% bau mulut dari bakteria lidah!", points: 100, health: 20, unlock: "👅 Lencana Nafas Segar" },
          { label: "B", text: "Cadangkan kunyah gula-gula getah selalu.", result: "okay", feedback: "✅ Tutup bau tapi tidak selesai punca!", points: 50, health: 5 },
          { label: "C", text: "Beritahu itu genetik, tiada apa boleh dibuat.", result: "wrong", feedback: "❌ Bau mulut biasanya dari bakteria lidah — boleh dirawat!", points: 0, health: -15 },
        ],
      },
      { id: 6, emoji: "🎂", title: "Snek Hari Jadi", category: "nutrition",
        scenario: "Kamu di parti hari jadi dengan kek, gula-gula, dan buah-buahan.",
        options: [
          { label: "A", text: "Makan manisan sepanjang parti.", result: "wrong", feedback: "❌ Gula berterusan = serangan asid berterusan pada gigi!", points: 0, health: -15 },
          { label: "B", text: "Makan manisan satu kali, kemudian buah dan keju.", result: "best", feedback: "⭐ Bijak! Kurang dedahan gula melindungi gigi!", points: 100, health: 20, unlock: "🎯 Lencana Snek Bijak" },
          { label: "C", text: "Langkau semua manisan sepenuhnya.", result: "okay", feedback: "✅ Sangat ketat tapi selamat. Sederhana juga ok!", points: 50, health: 8 },
        ],
        promotion: { fromKey: 1, toKey: 2, emoji: "🏆" },
      },
      { id: 7, emoji: "💨", title: "Trend Vape", category: "lifestyle",
        scenario: "Rakan sekelas tawarkan vape, kata \"ia hanya wap berperisa, selamat.\"",
        options: [
          { label: "A", text: "Tolak — vape masih merosakkan kesihatan oral.", result: "best", feedback: "⭐ Bijak! Vape juga sebabkan penyakit gusi dan mulut kering!", points: 100, health: 20, unlock: "💨 Lencana Bebas Vape" },
          { label: "B", text: "Cuba — ia hanya air berperisa.", result: "wrong", feedback: "❌ Vape ada nikotin yang merosakkan gusi dan keringkan mulut!", points: 0, health: -20 },
          { label: "C", text: "Hisap sedikit, kemudian tolak.", result: "wrong", feedback: "❌ Satu hisapan pun dedahkan kepada bahan kimia merbahaya!", points: 0, health: -10 },
        ],
      },
      { id: 8, emoji: "🦷", title: "Sakit Gigi Bongsu", category: "professional",
        scenario: "Gusi belakang kamu bengkak dan sakit. Mak cik kata gigi bongsu sedang tumbuh.",
        options: [
          { label: "A", text: "Jumpa doktor untuk X-ray dan penilaian.", result: "best", feedback: "⭐ Bijak! Penilaian awal elak pembedahan besar nanti!", points: 100, health: 20, unlock: "🔬 Kuasa Penglihatan X-Ray" },
          { label: "B", text: "Ambil ubat tahan sakit dan abaikan.", result: "wrong", feedback: "❌ Ubat tahan sakit tutup masalah — jangkitan boleh merebak!", points: 0, health: -10 },
          { label: "C", text: "Tunggu sahaja — akan hilang sendiri.", result: "wrong", feedback: "❌ Gigi bongsu tersangkut boleh berjangkit — perlu pemeriksaan!", points: 0, health: -15 },
        ],
      },
      { id: 9, emoji: "📞", title: "Teledentistry", category: "technology",
        scenario: "Kampung kamu tiada doktor gigi. Aplikasi baru tawarkan perundingan video.",
        options: [
          { label: "A", text: "Cuba perundingan video untuk nasihat.", result: "best", feedback: "⭐ Brilliant! Telehealth bawa penjagaan ke kawasan terpencil!", points: 100, health: 20, unlock: "📞 Inovator Telehealth" },
          { label: "B", text: "Tunggu sehingga boleh ke bandar.", result: "okay", feedback: "✅ Berhati-hati tapi melengahkan penjagaan!", points: 50, health: 5 },
          { label: "C", text: "Tidak percaya doktor dalam talian.", result: "wrong", feedback: "❌ Teledentistry adalah perubatan disahkan — kamu hilang penjagaan berharga!", points: 0, health: -10 },
        ],
        promotion: { fromKey: 2, toKey: 3, emoji: "🌟" },
      },
    ],
  },
  set3: {
    en: [
      { id: 1, emoji: "⚡", title: "Electric vs Manual", category: "prevention",
        scenario: "Your dad has arthritis and struggles to brush manually with proper technique.",
        options: [
          { label: "A", text: "Tell him to skip brushing some days when his hand hurts.", result: "wrong", feedback: "❌ Skipping causes plaque buildup. Electric brush solves the real problem!", points: 0, health: -10 },
          { label: "B", text: "Suggest an electric toothbrush — easier and more effective.", result: "best", feedback: "⭐ Excellent! Electric brushes are great for limited mobility and remove more plaque!", points: 100, health: 20, unlock: "⚡ Power Brush Badge" },
          { label: "C", text: "Tell him to brush harder to compensate.", result: "wrong", feedback: "❌ Hard brushing damages enamel and gums — the opposite of what you need!", points: 0, health: -15 },
        ],
      },
      { id: 2, emoji: "🏷️", title: "Hidden Sugars", category: "nutrition",
        scenario: "Mom buys \"sugar-free\" yogurt for your sibling. You read labels and find lots of hidden sugars.",
        options: [
          { label: "A", text: "Stay quiet — Mom knows best.", result: "wrong", feedback: "❌ \"Sugar-free\" can mean no added sugar but high natural sugar — knowledge helps!", points: 0, health: -10 },
          { label: "B", text: "Show her the label — explain hidden sugar names like fructose, maltose.", result: "best", feedback: "⭐ Brilliant! Reading labels is a superpower for oral health!", points: 100, health: 20, unlock: "🏷️ Label Reader Badge" },
          { label: "C", text: "Throw the yogurt away.", result: "wrong", feedback: "❌ Wasteful and rude. Education is better than confrontation!", points: 0, health: -10 },
        ],
      },
      { id: 3, emoji: "🌳", title: "Root Canal Truth", category: "professional",
        scenario: "Your uncle refuses a root canal, saying \"it's better to just extract the tooth.\"",
        options: [
          { label: "A", text: "Stay neutral — let him decide alone.", result: "okay", feedback: "✅ Respectful, but you missed a chance to share life-changing knowledge!", points: 50, health: 5 },
          { label: "B", text: "Explain root canals save the tooth and aren't painful with anesthesia.", result: "best", feedback: "⭐ Spot on! Modern root canals are 95% successful and pain-free!", points: 100, health: 20, unlock: "🌳 Tooth Saver Badge" },
          { label: "C", text: "Agree — extraction is simpler and cheaper.", result: "wrong", feedback: "❌ Saving natural teeth is always best! Extraction leads to other dental problems!", points: 0, health: -15 },
        ],
        promotion: { fromKey: 0, toKey: 1, emoji: "🎓" },
      },
      { id: 4, emoji: "🤰", title: "Pregnancy Care", category: "lifestyle",
        scenario: "Your pregnant cousin avoids the dentist, fearing it's unsafe for her baby.",
        options: [
          { label: "A", text: "Encourage second-trimester check-up — it's safe AND important.", result: "best", feedback: "⭐ Excellent! Dental care during pregnancy protects mom AND baby!", points: 100, health: 20, unlock: "🤰 Maternal Health Badge" },
          { label: "B", text: "Agree — wait until after the baby is born.", result: "wrong", feedback: "❌ Untreated gum disease during pregnancy increases premature birth risk!", points: 0, health: -15 },
          { label: "C", text: "Tell her to just brush more often.", result: "wrong", feedback: "❌ Brushing alone can't address pregnancy-related dental risks!", points: 0, health: -10 },
        ],
      },
      { id: 5, emoji: "😰", title: "Dental Anxiety", category: "professional",
        scenario: "Your little brother has panic attacks before every dentist visit.",
        options: [
          { label: "A", text: "Talk to dentist about sedation or kid-friendly clinics.", result: "best", feedback: "⭐ Compassionate! Special clinics use distraction and gentle care!", points: 100, health: 20, unlock: "💚 Comfort Care Badge" },
          { label: "B", text: "Force him to go anyway — he'll get over it.", result: "wrong", feedback: "❌ Forcing worsens dental phobia for life. Empathy works better!", points: 0, health: -15 },
          { label: "C", text: "Let him skip dental visits to avoid stress.", result: "wrong", feedback: "❌ Avoidance causes much bigger problems later!", points: 0, health: -10 },
        ],
      },
      { id: 6, emoji: "✨", title: "DIY Whitening Trap", category: "lifestyle",
        scenario: "Your friend wants to try viral \"DIY teeth whitening\" with lemon and baking soda.",
        options: [
          { label: "A", text: "Try it — it's natural so it must be safe.", result: "wrong", feedback: "❌ Acid + abrasion permanently damages enamel — natural ≠ safe!", points: 0, health: -20 },
          { label: "B", text: "Try just once to see what happens.", result: "wrong", feedback: "❌ Even one use can cause permanent enamel damage!", points: 0, health: -10 },
          { label: "C", text: "Discourage — recommend dentist-approved whitening only.", result: "best", feedback: "⭐ Wise! Professional whitening is safe and effective!", points: 100, health: 20, unlock: "✨ Safe Smile Badge" },
        ],
        promotion: { fromKey: 1, toKey: 2, emoji: "🏆" },
      },
      { id: 7, emoji: "🎗️", title: "Oral Cancer Warning", category: "lifestyle",
        scenario: "Your grandfather has a sore in his mouth that hasn't healed in 3 weeks.",
        options: [
          { label: "A", text: "It's just a regular ulcer — ignore it.", result: "wrong", feedback: "❌ Sores lasting over 2 weeks can be early oral cancer signs!", points: 0, health: -20 },
          { label: "B", text: "Insist he see a dentist immediately for screening.", result: "best", feedback: "⭐ Lifesaver! Early oral cancer detection has 90% survival rate!", points: 100, health: 25, unlock: "🎗️ Cancer Awareness Badge" },
          { label: "C", text: "Apply traditional remedies and wait.", result: "wrong", feedback: "❌ Delay can be deadly with oral cancer!", points: 0, health: -15 },
        ],
      },
      { id: 8, emoji: "🩺", title: "Diabetes Connection", category: "professional",
        scenario: "Your aunt has diabetes and frequent gum infections. She thinks they're unrelated.",
        options: [
          { label: "A", text: "Explain the link — she needs extra dental care.", result: "best", feedback: "⭐ Excellent! Oral health affects whole-body health!", points: 100, health: 20, unlock: "🩺 Whole Body Health Badge" },
          { label: "B", text: "Agree — diabetes and gums aren't connected.", result: "wrong", feedback: "❌ Strong link! Diabetes worsens gum disease, gum disease worsens diabetes!", points: 0, health: -15 },
          { label: "C", text: "Suggest she just take antibiotics.", result: "wrong", feedback: "❌ Antibiotics don't address the diabetes-gum cycle!", points: 0, health: -10 },
        ],
      },
      { id: 9, emoji: "🤖", title: "AI in Dentistry", category: "technology",
        scenario: "A new clinic uses AI to detect cavities from X-rays, sometimes catching what dentists miss.",
        options: [
          { label: "A", text: "Refuse — AI can't replace doctors.", result: "wrong", feedback: "❌ AI assists, doesn't replace! It catches issues humans might miss!", points: 0, health: -10 },
          { label: "B", text: "Embrace AI as a tool — it helps catch issues earlier.", result: "best", feedback: "⭐ Future-ready! AI + dentist = best detection rates!", points: 100, health: 20, unlock: "🤖 AI Pioneer Badge" },
          { label: "C", text: "Trust only AI, skip the dentist's opinion.", result: "wrong", feedback: "❌ AI is a tool, not a replacement! Combined approach is best!", points: 0, health: -10 },
        ],
        promotion: { fromKey: 2, toKey: 3, emoji: "🌟" },
      },
    ],
    my: [
      { id: 1, emoji: "⚡", title: "Elektrik vs Manual", category: "prevention",
        scenario: "Ayah kamu ada artritis dan susah memberus dengan teknik betul.",
        options: [
          { label: "A", text: "Suruh dia langkau memberus bila tangan sakit.", result: "wrong", feedback: "❌ Melangkau menyebabkan plak terbina!", points: 0, health: -10 },
          { label: "B", text: "Cadangkan berus elektrik — lebih mudah dan berkesan.", result: "best", feedback: "⭐ Cemerlang! Berus elektrik bagus untuk pergerakan terhad!", points: 100, health: 20, unlock: "⚡ Lencana Berus Berkuasa" },
          { label: "C", text: "Suruh memberus lebih kuat untuk mengimbangi.", result: "wrong", feedback: "❌ Memberus kuat rosakkan enamel — sebaliknya dari yang diperlukan!", points: 0, health: -15 },
        ],
      },
      { id: 2, emoji: "🏷️", title: "Gula Tersembunyi", category: "nutrition",
        scenario: "Mak beli yogurt \"tanpa gula\" untuk adik. Kamu baca label dan jumpa banyak gula tersembunyi.",
        options: [
          { label: "A", text: "Senyap sahaja — Mak lebih tahu.", result: "wrong", feedback: "❌ \"Tanpa gula\" boleh bermaksud tiada gula tambahan tapi gula semula jadi tinggi!", points: 0, health: -10 },
          { label: "B", text: "Tunjuk label — terangkan nama gula tersembunyi seperti fruktosa.", result: "best", feedback: "⭐ Brilliant! Membaca label adalah kuasa hebat untuk kesihatan oral!", points: 100, health: 20, unlock: "🏷️ Lencana Pembaca Label" },
          { label: "C", text: "Buang yogurt itu sahaja.", result: "wrong", feedback: "❌ Membazir dan kurang sopan!", points: 0, health: -10 },
        ],
      },
      { id: 3, emoji: "🌳", title: "Kebenaran Rawatan Akar", category: "professional",
        scenario: "Pak cik kamu tolak rawatan akar, kata \"lebih baik cabut sahaja.\"",
        options: [
          { label: "A", text: "Diam — biar dia putuskan sendiri.", result: "okay", feedback: "✅ Hormat, tapi terlepas peluang berkongsi pengetahuan penting!", points: 50, health: 5 },
          { label: "B", text: "Jelaskan rawatan akar selamatkan gigi dan tidak sakit dengan bius.", result: "best", feedback: "⭐ Tepat! Rawatan akar moden 95% berjaya dan tanpa sakit!", points: 100, health: 20, unlock: "🌳 Lencana Penyelamat Gigi" },
          { label: "C", text: "Bersetuju — cabut lebih mudah dan murah.", result: "wrong", feedback: "❌ Selamatkan gigi asli sentiasa terbaik!", points: 0, health: -15 },
        ],
        promotion: { fromKey: 0, toKey: 1, emoji: "🎓" },
      },
      { id: 4, emoji: "🤰", title: "Penjagaan Mengandung", category: "lifestyle",
        scenario: "Sepupu hamil kamu elak doktor gigi, takut tidak selamat untuk bayi.",
        options: [
          { label: "A", text: "Galakkan pemeriksaan trimester kedua — selamat dan penting.", result: "best", feedback: "⭐ Cemerlang! Penjagaan gigi semasa hamil melindungi ibu DAN bayi!", points: 100, health: 20, unlock: "🤰 Lencana Kesihatan Ibu" },
          { label: "B", text: "Bersetuju — tunggu selepas bayi lahir.", result: "wrong", feedback: "❌ Penyakit gusi tidak dirawat semasa hamil tingkatkan risiko bersalin pramatang!", points: 0, health: -15 },
          { label: "C", text: "Suruh dia memberus lebih kerap sahaja.", result: "wrong", feedback: "❌ Memberus sahaja tidak boleh atasi risiko gigi semasa hamil!", points: 0, health: -10 },
        ],
      },
      { id: 5, emoji: "😰", title: "Kebimbangan Gigi", category: "professional",
        scenario: "Adik lelaki kamu ada serangan panik sebelum setiap lawatan doktor gigi.",
        options: [
          { label: "A", text: "Bincang dengan doktor tentang sedasi atau klinik mesra kanak-kanak.", result: "best", feedback: "⭐ Penyayang! Klinik khas guna pengalihan dan penjagaan lembut!", points: 100, health: 20, unlock: "💚 Lencana Penjagaan Selesa" },
          { label: "B", text: "Paksa dia pergi — dia akan terbiasa.", result: "wrong", feedback: "❌ Memaksa burukkan fobia seumur hidup. Empati lebih baik!", points: 0, health: -15 },
          { label: "C", text: "Biar dia langkau lawatan untuk elak tekanan.", result: "wrong", feedback: "❌ Penghindaran sebabkan masalah lebih besar nanti!", points: 0, health: -10 },
        ],
      },
      { id: 6, emoji: "✨", title: "Perangkap DIY Pemutih", category: "lifestyle",
        scenario: "Kawan kamu nak cuba \"pemutih gigi DIY\" viral dengan lemon dan baking soda.",
        options: [
          { label: "A", text: "Cuba — semula jadi jadi mesti selamat.", result: "wrong", feedback: "❌ Asid + lelasan rosakkan enamel selamanya — semula jadi ≠ selamat!", points: 0, health: -20 },
          { label: "B", text: "Cuba sekali sahaja untuk lihat.", result: "wrong", feedback: "❌ Sekali pun boleh sebabkan kerosakan enamel kekal!", points: 0, health: -10 },
          { label: "C", text: "Halang — cadangkan pemutih disahkan doktor sahaja.", result: "best", feedback: "⭐ Bijak! Pemutih profesional selamat dan berkesan!", points: 100, health: 20, unlock: "✨ Lencana Senyum Selamat" },
        ],
        promotion: { fromKey: 1, toKey: 2, emoji: "🏆" },
      },
      { id: 7, emoji: "🎗️", title: "Amaran Kanser Mulut", category: "lifestyle",
        scenario: "Datuk kamu ada luka dalam mulut yang tidak sembuh selama 3 minggu.",
        options: [
          { label: "A", text: "Itu ulser biasa sahaja — abaikan.", result: "wrong", feedback: "❌ Luka lebih 2 minggu boleh jadi tanda awal kanser mulut!", points: 0, health: -20 },
          { label: "B", text: "Desak dia jumpa doktor segera untuk saringan.", result: "best", feedback: "⭐ Penyelamat! Pengesanan awal kanser mulut beri 90% kadar hidup!", points: 100, health: 25, unlock: "🎗️ Lencana Kesedaran Kanser" },
          { label: "C", text: "Sapu ubat tradisional dan tunggu.", result: "wrong", feedback: "❌ Lambat boleh maut dengan kanser mulut!", points: 0, health: -15 },
        ],
      },
      { id: 8, emoji: "🩺", title: "Hubungan Diabetes", category: "professional",
        scenario: "Mak cik kamu ada diabetes dan jangkitan gusi kerap. Dia fikir tiada kaitan.",
        options: [
          { label: "A", text: "Jelaskan kaitan — dia perlu penjagaan gigi tambahan.", result: "best", feedback: "⭐ Cemerlang! Kesihatan oral pengaruhi seluruh badan!", points: 100, health: 20, unlock: "🩺 Lencana Kesihatan Menyeluruh" },
          { label: "B", text: "Bersetuju — diabetes dan gusi tiada kaitan.", result: "wrong", feedback: "❌ Hubungan kuat! Diabetes burukkan gusi, gusi burukkan diabetes!", points: 0, health: -15 },
          { label: "C", text: "Suruh dia ambil antibiotik sahaja.", result: "wrong", feedback: "❌ Antibiotik tidak selesaikan kitaran diabetes-gusi!", points: 0, health: -10 },
        ],
      },
      { id: 9, emoji: "🤖", title: "AI dalam Pergigian", category: "technology",
        scenario: "Klinik baru guna AI untuk kesan kaviti dari X-ray, kadang kala tangkap apa doktor terlepas.",
        options: [
          { label: "A", text: "Tolak — AI tidak boleh ganti doktor.", result: "wrong", feedback: "❌ AI bantu, bukan ganti! Ia tangkap masalah yang manusia mungkin terlepas!", points: 0, health: -10 },
          { label: "B", text: "Terima AI sebagai alat — ia bantu kesan masalah lebih awal.", result: "best", feedback: "⭐ Bersedia masa depan! AI + doktor = pengesanan terbaik!", points: 100, health: 20, unlock: "🤖 Lencana Perintis AI" },
          { label: "C", text: "Percaya AI sahaja, langkau pendapat doktor.", result: "wrong", feedback: "❌ AI alat, bukan pengganti! Pendekatan gabungan terbaik!", points: 0, health: -10 },
        ],
        promotion: { fromKey: 2, toKey: 3, emoji: "🌟" },
      },
    ],
  },
};

export const RANK_EMOJIS = ["🩺", "🎓", "🏆", "🌟"];
export const SET_KEYS = ["set1", "set2", "set3"];
